// Generado automáticamente por python-bridge/generate_trivia.py desde el catálogo real.
// Pregunta: '¿De qué banda o artista es la canción X?' con 4 opciones.
export const triviaQuestions = [
  { song: "Fade To Black", artist: "Metallica", options: ["Godsmack", "Versailles", "A. J. Ghent", "Metallica"], answer: 3 },
  { song: "One", artist: "Metallica", options: ["Nightwish", "Till Lindemann", "Metallica", "Pentagram"], answer: 2 },
  { song: "Never Enough", artist: "The Cure", options: ["NEVERMORE", "The Cure", "The Coathangers", "Motionless in White"], answer: 1 },
  { song: "The Lovecats", artist: "The Cure", options: ["Halestorm", "Versailles", "The Cure", "Imagine Dragons"], answer: 2 },
  { song: "In Bloom", artist: "Nirvana", options: ["The Winery Dogs", "Nirvana", "The Cardigans", "The Handsome Family"], answer: 1 },
  { song: "Where did you sleep last night", artist: "Nirvana", options: ["Vision Divine", "Mando Diao", "Nirvana", "The Knack"], answer: 2 },
  { song: "Hysteria", artist: "Muse", options: ["Muse", "Black Sabbath", "Killswitch Engage", "OMNIUM GATHERUM"], answer: 0 },
  { song: "Stockholm Syndrome", artist: "Muse", options: ["Midnight Oil", "Chris Isaak", "Aerosmith", "Muse"], answer: 3 },
  { song: "Live Wire", artist: "Mötley Crüe", options: ["Rush", "VIGIL OF WAR", "QUEENSRŸCHE", "Mötley Crüe"], answer: 3 },
  { song: "Like A Virgin", artist: "Mötley Crüe", options: ["sky valley mistress", "Foo Fighters", "Breaking Benjamin", "Mötley Crüe"], answer: 3 },
  { song: "In The End", artist: "Linkin Park", options: ["TELEPHONE", "SOULFLY", "Linkin Park", "The Sisters Of Mercy"], answer: 2 },
  { song: "Over Each Other", artist: "Linkin Park", options: ["ICED EARTH", "Linkin Park", "T. Rex", "Samantha Fish"], answer: 1 },
  { song: "The World Is Not Enough", artist: "Garbage", options: ["Garbage", "MUSE", "EXODUS", "Queens Of The Stone Age"], answer: 0 },
  { song: "The Men Who Rule The World", artist: "Garbage", options: ["Machine Gun Kelly", "TELEPHONE", "Garbage", "Bersuit Vergarabat"], answer: 2 },
  { song: "Under Pressure", artist: "Queen", options: ["La Polla Records", "Queen", "Los Enanitos Verdes", "ozzy osbourne"], answer: 1 },
  { song: "Stone Cold Crazy", artist: "Queen", options: ["Kittie", "Aerosmith", "Queen", "Blink-182"], answer: 2 },
  { song: "Live And Let Die", artist: "Guns N' Roses", options: ["VERSUS THEM", "Steppenwolf", "Guns N' Roses", "JINJER"], answer: 2 },
  { song: "Estranged", artist: "Guns N' Roses", options: ["Guns N' Roses", "Interpol", "PAIN OF SALVATION", "MYRATH"], answer: 0 },
  { song: "Times Like These", artist: "Foo Fighters", options: ["Motionless In White", "OK Go", "Foo Fighters", "Bring Me The Horizon"], answer: 2 },
  { song: "Big Me", artist: "Foo Fighters", options: ["Marilyn manson", "Foo Fighters", "Slayer", "Janis Joplin"], answer: 1 },
  { song: "clint eastwood", artist: "Gorillaz", options: ["The Beaches", "The Fratellis", "Gorillaz", "Bad Religion"], answer: 2 },
  { song: "Kids With Guns", artist: "Gorillaz", options: ["DEATHSTARS", "ARCH ENEMY", "Steven Wilson", "Gorillaz"], answer: 3 },
  { song: "Diamonds", artist: "Imelda May", options: ["Nekrogoblikon", "The Fuzztones", "The Beaches", "Imelda May"], answer: 3 },
  { song: "Should've Been You", artist: "Imelda May", options: ["Celtas cortos", "Imelda May", "Paramore", "The xx"], answer: 1 },
  { song: "2 Minutes To Midnight", artist: "Iron Maiden", options: ["Goo Goo Dolls", "La Pulqueria", "Iron Maiden", "MANEGARM"], answer: 2 },
  { song: "The Prisoner", artist: "Iron Maiden", options: ["Iron Maiden", "dire straits", "JET", "HIM"], answer: 0 },
  { song: "Freak on a Leash", artist: "Korn", options: ["Korn", "The White Stripes", "OK Go", "TRIPTYKON"], answer: 0 },
  { song: "Blind", artist: "Korn", options: ["Infected Rain", "Korn", "Delta 5", "PASSENGER"], answer: 1 },
  { song: "Sugar Kane", artist: "Sonic Youth", options: ["picture me broken", "Pentakill", "Sonic Youth", "Them Crooked Vultures"], answer: 2 },
  { song: "Kool Thing", artist: "Sonic Youth", options: ["Sonic Youth", "fall out boy", "4 Non Blondes", "Black Label Society"], answer: 0 },
  { song: "People Are Strange", artist: "The Doors", options: ["Queens of the Stone Age", "The Wild Dukes", "The Doors", "Loquillo"], answer: 2 },
  { song: "The End", artist: "The Doors", options: ["Crash Test Dummies", "Joan Jett", "The Doors", "VOLTURIAN"], answer: 2 },
  { song: "Shoot To Thrill", artist: "AC DC", options: ["AC DC", "Rhapsody", "the Rolling Stones", "Ram Jam"], answer: 0 },
  { song: "Big Gun", artist: "AC DC", options: ["Godsmack", "TEMPERANCE", "AC DC", "Red Fang"], answer: 2 },
  { song: "Planet Caravan", artist: "Black Sabbath", options: ["BLACK STAR RIDERS", "Deap Vally", "Mastodon", "Black Sabbath"], answer: 3 },
  { song: "Fairies Wear Boots", artist: "Black Sabbath", options: ["The Jon Spencer Blues Explosion", "Black Sabbath", "Johnny Cash", "The Smashing Pumpkins"], answer: 1 },
  { song: "Year zero", artist: "Ghost", options: ["GRAND FUNK RAILROAD", "Ievan Polkka", "ozzy osbourne", "Ghost"], answer: 3 },
  { song: "Dance Macabre", artist: "Ghost", options: ["Gary Clark Jr", "Cuca", "Galadriel", "Ghost"], answer: 3 },
  { song: "Rock And Roll", artist: "Led Zeppelin", options: ["Wolfmother", "The Virginmarys", "Led Zeppelin", "GALNERYUS"], answer: 2 },
  { song: "When The Levee Breaks", artist: "Led Zeppelin", options: ["Black Sabbath", "Alannah Myles", "Led Zeppelin", "Femme Fatale"], answer: 2 },
  { song: "In My Darkest Hour", artist: "Megadeth", options: ["Megadeth", "ROSENDO", "The Black Veil Brides", "Razorlight"], answer: 0 },
  { song: "She Wolf", artist: "Megadeth", options: ["Stratovarius", "Sleeping With Sirens", "Silversun Pickups", "Megadeth"], answer: 3 },
  { song: "Debaser", artist: "Pixies", options: ["Eric Clapton", "Pixies", "SiM", "SENTENCED"], answer: 1 },
  { song: "This Monkeys Gone To Heaven", artist: "Pixies", options: ["Pixies", "Wintersun", "The Black Veil Brides", "Kiss"], answer: 0 },
  { song: "Green Heaven", artist: "Red Hot Chili Peppers", options: ["John Fairhurst", "Trivium", "Red Hot Chili Peppers", "Audioslave"], answer: 2 },
  { song: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", options: ["HALCYON WAY", "Iron Butterfly", "the Cranberries", "Red Hot Chili Peppers"], answer: 3 },
  { song: "Spoonman", artist: "Soundgarden", options: ["Imelda May", "airbourne", "Soundgarden", "Santana"], answer: 2 },
  { song: "Fell On Black Days", artist: "Soundgarden", options: ["The Jimi Hendrix Experience", "BLUES PILLS", "DAERIA", "Soundgarden"], answer: 3 },
  { song: "Spiders", artist: "System Of A Down", options: ["Joe Cocker", "Bullet For My Valentine", "System Of A Down", "Pearl Jam"], answer: 2 },
  { song: "Suggestions", artist: "System Of A Down", options: ["System Of A Down", "BURNING WITCHES", "Roxette", "John Fairhurst"], answer: 0 },
  { song: "Blow Up", artist: "The Beaches", options: ["Madness", "The Virginmarys", "The Beaches", "Fito y Fitipaldis"], answer: 2 },
  { song: "Money", artist: "The Beaches", options: ["All Them Witches", "The Beaches", "PUSCIFER", "SYMPHONY X"], answer: 1 },
  { song: "Only Love Can Save Me Now", artist: "The Pretty Reckless", options: ["The Pretty Reckless", "Faith No More", "After The Burial", "Alannah Myles"], answer: 0 },
  { song: "My Medicine", artist: "The Pretty Reckless", options: ["Ievan Polkka", "The Pretty Reckless", "George Baker", "Lung Leg"], answer: 1 },
  { song: "Livin' On The Edge", artist: "Aerosmith", options: ["Radkey", "Violent Soho", "Die Dorks", "Aerosmith"], answer: 3 },
  { song: "I Don't Want to Miss a Thing", artist: "Aerosmith", options: ["Jehnny Beth", "Pat Benatar", "Aerosmith", "Sons And Daughters"], answer: 2 },
  { song: "Tears Dont Fall", artist: "Bullet For My Valentine", options: ["Sloy", "FLOTSAM AND JETSAM", "Mr. Big", "Bullet For My Valentine"], answer: 3 },
  { song: "Your Betrayal", artist: "Bullet For My Valentine", options: ["Les Claypool", "the Pretty Reckless", "Bullet For My Valentine", "Zeraphine"], answer: 2 },
  { song: "Space Oddity", artist: "David Bowie", options: ["David Bowie", "El Gran Silencio", "Jet", "Wintersun"], answer: 0 },
  { song: "Modern Love", artist: "David Bowie", options: ["David Bowie", "Soziedad Alkoholika", "Molotov", "quiet riot"], answer: 0 },
  { song: "THE PURGE", artist: "In This Moment", options: ["Creedence Clearwater Revival", "Dire Straits", "In This Moment", "Smash Mouth"], answer: 2 },
  { song: "Sex Metal Barbie", artist: "In This Moment", options: ["4 Non Blondes", "Joey Ramone", "In This Moment", "triana"], answer: 2 },
  { song: "Famous Last Words", artist: "My Chemical Romance", options: ["Bersuit Vergarabat", "Kings Of Leon", "My Chemical Romance", "Her"], answer: 2 },
  { song: "Teenagers", artist: "My Chemical Romance", options: ["AGAINST MYSELF", "My Chemical Romance", "Escape The Fate", "Plush"], answer: 1 },
  { song: "Do the Evolution", artist: "Pearl Jam", options: ["Protest The Hero", "Pearl Jam", "Korn", "LACUNA COIL"], answer: 1 },
  { song: "Mother", artist: "Pearl Jam", options: ["Pearl Jam", "Chicago", "Bif Naked", "The Living End"], answer: 0 },
  { song: "Dicke Titten", artist: "Rammstein", options: ["Anteros", "THE NIGHT FLIGHT ORCHESTRA", "Rammstein", "Horrorpops"], answer: 2 },
  { song: "Seemann", artist: "Rammstein", options: ["Guns N' Roses", "Heavy Tiger", "Rammstein", "Pulp"], answer: 2 },
  { song: "Bimbo", artist: "The Coathangers", options: ["Smash Mouth", "Disturbed", "The Proclaimers", "The Coathangers"], answer: 3 },
  { song: "Perfume", artist: "The Coathangers", options: ["Tool", "The Coathangers", "John Fairhurst", "Maeder"], answer: 1 },
  { song: "Ball and biscuit", artist: "The White Stripes", options: ["Protest The Hero", "Ievan Polkka", "The White Stripes", "Dick Dale and His Del-Tones"], answer: 2 },
  { song: "Icky Thump", artist: "The White Stripes", options: ["Pantera", "TALKING HEADS", "Bonnie Tyler", "The White Stripes"], answer: 3 },
  { song: "R U Mine", artist: "Arctic Monkeys", options: ["Escape The Fate", "Arctic Monkeys", "Hey! Hello!", "Kasabian"], answer: 1 },
  { song: "No 1 Party Anthem", artist: "Arctic Monkeys", options: ["Butcher Babies", "Blondie", "Arctic Monkeys", "Inglorious"], answer: 2 },
  { song: "Good Riddance (Time of Your Life)", artist: "Green Day", options: ["Kortatu", "Green Day", "Skid Row", "Gary Clark Jr."], answer: 1 },
  { song: "Basket Case", artist: "Green Day", options: ["jinjer", "OMNIUM GATHERUM", "My Bloody Valentine", "Green Day"], answer: 3 },
  { song: "Shadowplay", artist: "Joy Division", options: ["Joy Division", "VEIL OF MAYA", "Journey", "The Black Keys"], answer: 0 },
  { song: "Love Will Tear Us Apart", artist: "Joy Division", options: ["The Waterboys", "BAD OMENS", "Belly", "Joy Division"], answer: 3 },
  { song: "We Are 138", artist: "Misfits", options: ["The Runaways", "SYNLAKROSS", "Misfits", "Ghost"], answer: 2 },
  { song: "20 Eyes", artist: "Misfits", options: ["Misfits", "Reckless Love", "Marea", "ozzy osbourne"], answer: 0 },
  { song: "Tales Of Glory", artist: "Motörhead", options: ["IDLES", "Motörhead", "Deftones", "Limp Bizkit"], answer: 1 },
  { song: "Thunder and Lightning", artist: "Motörhead", options: ["Motörhead", "JINJER", "Wolfchant", "The Cardigans"], answer: 0 },
  { song: "Regret", artist: "New Order", options: ["New Order", "Cradle Of Filth", "McFly", "EPICA"], answer: 0 },
  { song: "True Faith", artist: "New Order", options: ["New Order", "BORKNAGAR", "Interpol", "Viejas Locas"], answer: 0 },
  { song: "Misery Business", artist: "Paramore", options: ["Queens Of The Stone Age", "Gary Moore", "Paramore", "Chris Cornell"], answer: 2 },
  { song: "Still Into You", artist: "Paramore", options: ["the Undertones", "Razorlight", "CHICKENFOOT", "Paramore"], answer: 3 },
  { song: "Shine On You Crazy Diamond", artist: "Pink Floyd", options: ["Molotov", "Pink Floyd", "Rob Zombie", "Sons And Daughters"], answer: 1 },
  { song: "Hey You", artist: "Pink Floyd", options: ["The Handsome Family", "Pink Floyd", "R.E.M.", "INXS"], answer: 1 },
  { song: "Lotus Flower", artist: "Radiohead", options: ["Radiohead", "The Strokes", "NITA STRAUSS", "The Beatles"], answer: 0 },
  { song: "High and Dry", artist: "Radiohead", options: ["Stevie Nicks", "Radiohead", "Iron Butterfly", "AVANTASIA"], answer: 1 },
  { song: "Freak", artist: "SYNLAKROSS", options: ["Ramones", "AC DC", "SYNLAKROSS", "Glenn Hughes"], answer: 2 },
  { song: "Curly Wolves", artist: "SYNLAKROSS", options: ["SYNLAKROSS", "Stealers Wheel", "Roxette", "Siouxsie And The Banshees"], answer: 0 },
  { song: "Maps", artist: "Yeah Yeah Yeahs", options: ["Angra", "Yeah Yeah Yeahs", "Admiral Sir Cloudesley Shovell", "Jarvis Cocker"], answer: 1 },
  { song: "Sacrilege", artist: "Yeah Yeah Yeahs", options: ["Suzi Quatro", "Godsmack", "Yeah Yeah Yeahs", "We Are Harlot"], answer: 2 },
  { song: "Over My Head", artist: "Alabama Shakes", options: ["Alabama Shakes", "Theatres des Vampires", "Papa Roach", "Molotov"], answer: 0 },
  { song: "I Ain't The Same", artist: "Alabama Shakes", options: ["The Cramps", "Alabama Shakes", "Ram Jam", "Beastie Boys"], answer: 1 },
  { song: "Them Bones", artist: "Alice In Chains", options: ["Crash Test Dummies", "Alice In Chains", "Iron Butterfly", "Black Sabbath"], answer: 1 },
  { song: "Would", artist: "Alice In Chains", options: ["Deaf Devils", "Silverchair", "Alice In Chains", "Terminal Choice"], answer: 2 },
  { song: "Call Me", artist: "Blondie", options: ["The Birthday Massacre", "Pearl Jam", "Blondie", "The Fuzztones"], answer: 2 },
  { song: "Dreaming", artist: "Blondie", options: ["ARCANE DIVIDE", "Blondie", "MAD SIN", "Golden Earring"], answer: 1 },
];

export default triviaQuestions;
